### ISSUE TITLE
Add SiteURL before image path

### ISSUE THREAD

**Issue by poVoq** [mattermost/mattermost-plugin-memes#11]
I am running Mattermost with the bridgebot Matterbridge. When I post gifs from Discord for example the show up fine on Mattermost. But this plugin sends only a text like this:

`[success-kid](/plugins/memes/templates/success-kid.jpg?text=enables+memes+plugin&text=gets+all+the+people+to+switch+to+Mattermost)`

Would it be possible to (also?) post a functional URL and let Mattermost handle the display of the image? That way people on bridged channels also get to see the memes. Thanks!

**Comment by hanzei** [comment]
Sure this can be fixed. The line that has to be changed is https://github.com/mattermost/mattermost-plugin-memes/blob/master/server/plugin.go#L173

**Comment by hanzei** [comment]
This might also resolve https://github.com/mattermost/mattermost-plugin-memes/issues/11
