### ISSUE TITLE
"Unterminated single-quoted string" when trying to generate meme

### ISSUE THREAD

**Issue by chrisfromredfin** [mattermost/mattermost-plugin-memes#12]
```
{"level":"error","ts":1568314153.4204962,"caller":"mlog/log.go:172","msg":"error resolving meme","path":"/api/v4/commands/execute","request_id":"iq4rghosbjra5ececu1zg9ic4h","ip_addr":"98.2.226.53","user_id":"t6hzpmdfytgmunhrcy8bgzx5br","method":"POST","err_where":"ExecuteCommand","http_code":500,"err_details":"Unterminated single-quoted string"}
{"level":"error","ts":1568314538.1719606,"caller":"plugin/hclog_adapter.go:60","msg":"reading plugin stderr","plugin_id":"memes","wrapped_extras":"errorread |0: file already closed"}
```

I've just uninstall 1.0.0 and installed 1.1.1. I was seeing this behavior in 1.0.0 and so upgraded to try and fix. So I now have the latest release, BUT I am seeing this error in the logs. I also am seeing a broken image and the token for the meme when I press enter.

<img width="353" alt="Screen Shot 2019-09-12 at 3 10 00 PM" src="https://user-images.githubusercontent.com/278442/64813481-76a32400-d56f-11e9-8ec8-38f788aebeef.png">

then

<img width="237" alt="Screen Shot 2019-09-12 at 3 10 05 PM" src="https://user-images.githubusercontent.com/278442/64813487-7a36ab00-d56f-11e9-9659-1bd1fa5734c6.png">

Any thoughts?

**Comment by hanzei** [comment]
I can't reproduce your issue.

Steps:
1. Run MM 5.20
2. Install latest version of this plugin
3. Enter `/meme too-damn-high "it's to damn high."` in chat
4. See image posted successfully

**Comment by chrisfromredfin** [comment]
I'm using Gitlab omnibus version of mattermost, which is 5.17.3. It actually seems to be everything, not just ones with quotation marks, so I'm thinking the title of this is misleading at best, and is probably not an issue with the plugin at all.
