### ISSUE TITLE
Sort memes alphabetically in the list

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost/mattermost-plugin-memes#25]
Currently, the memes are ordered in the autocomplete feature, but not in the list of meme when `/meme` is called.

![image](https://user-images.githubusercontent.com/45119518/84180938-99c01d00-aa88-11ea-94b2-92663307a9c9.png)

It would be handy if they were sorted.

If we implement this change, can we implement the sort directly in `getAvailableMemes()` (`plugin.go`) as we always want them sorted ?

**Comment by hanzei** [comment]
Thanks for the suggestion @nathanaelhoun :+1: 

> If we implement this change, can we implement the sort directly in `getAvailableMemes()` (`plugin.go`) as we always want them sorted ?

That is totally reasonable.
