### ISSUE TITLE
Is this woking with 5.1

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-memes#3]
I would like to test it.

**Comment by amyblais** [comment]
Hi @uhlhosting,

I believe you'll find more info on this page: https://github.com/mattermost/mattermost-plugin-memes/releases.

Initial release requires Mattermost 4.6 or greater to run, v1.0 release will only work with Mattermost 5.2+ in the future.

**Comment by Hanzei** [comment]
@uhlhosting Can this issue be closed?

**Comment by uhlhosting** [comment]
Yes @amyblais please.
