### ISSUE TITLE
Add check for SiteURL presence to avoid panic

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-memes#33]
When the plugin starts up, it tries to [access the SiteURL](https://github.com/mattermost/mattermost-plugin-memes/blob/0f6783ceb65f877a383f9d1d5df4c1a1fa4e769f/server/plugin.go#L155), but this results in a nil pointer panic if the SiteURL is not set. We should instead ensure it is set, and return/log an error during `OnActivate` to make the error more visible.

**Comment by asimsedhain** [comment]
I would like to take this one.
