### ISSUE TITLE
Only the first two words are inserted

### ISSUE THREAD

**Issue by bmalsy** [mattermost/mattermost-plugin-memes#34]
When I execute the following command, only the first two words are inserted into the image.

`/meme aliens first line. second line`

![image](https://user-images.githubusercontent.com/52070921/91536927-c7916100-e915-11ea-9a6f-833337607466.png)

However, if I execute `/meme memes. memes everywhere`, the result is as in read me. It also works with other or more words, but not with defined memes.

**Comment by hanzei** [comment]
Spaces are used to separate the lines. Hence, you need to use `/meme aliens "first line." "second line"`.

**Comment by bmalsy** [comment]
Thanks so much, it works!
