### ISSUE TITLE
make: *** No rule to make target 'vendor'.  Stop.

### ISSUE THREAD

**Issue by xcamposdiaz** [mattermost/mattermost-plugin-memes#37]
Hello,

I've just installed a new Mattermost server in my school and I want to configure this plugin to make funnier to my students ... ;-)

I've cloned the git repo and follow the installation steps, but I've got this error:

   make: *** No rule to make target 'vendor'.  Stop.

I've no idea of programming, so sorry if my question is obvious. I think that the problem is that the file vendor doesn't exist in the folder of the plugin, but I clone it from the official source.

Any idea to help us?

Thanks,

**Comment by hanzei** [comment]
Hey @xcamposdiaz,

Thanks for trying out this plugin. You can install it directly from the Plugin Marketplace, which you can find under the Main Menu.

Let me know, if you where able to install the plugin.
