### ISSUE TITLE
Missing emojis since Mattermost 5.37

### ISSUE THREAD

**Issue by SunBlack** [mattermost/mattermost-plugin-memes#52]
After upgrading to Mattermost 5.37 we are missing some emojis (e.g. `:trollface:`). I believe we had this emoji because of this plugin

Could it be, that the emojis were custom emojis? Because there is a note in the [changelog](docs.mattermost.com/install/self-managed-changelog.html) of Mattermost.

> v5.37 adds support for emoji standard v13.0. If you have added a custom emoji in the past that uses one of the new system names, then that custom emoji is going to get overwritten by the system emoji. The workaround is to change the custom emoji name.

Or any other idea why we don't have these emojis anymore?

**Comment by hanzei** [comment]
@SunBlack How is your issue related to this plugin?

**Comment by SunBlack** [comment]
As it seems to was added here #46 - if you search for the icon in connection with Mattermost, the plugin is the only thing you find, so my guess was that the icons from the assets were also included as icons somehow. Of course, I could also be wrong.

**Comment by SunBlack** [comment]
After manually searching the Mattermost code, I found [where it was](https://github.com/mattermost/mattermost-webapp/blob/v5.36.2/utils/emoji.jsx). So I was wrong and it did not come from the plugin.
