### ISSUE TITLE
Doesn't work on fresh install

### ISSUE THREAD

**Issue by DavidIlie** [mattermost/mattermost-plugin-memes#54]
![image](https://user-images.githubusercontent.com/47594764/140904715-f63aa626-a452-4732-bd3a-84d97f362272.png)

This is my problem right now, it's a fresh install of mattermost, and I have installed and reinstalled the plugin several times and I still have the same problem. There is also nothing on the logs.

Can someone help?

**Comment by hanzei** [comment]
What MM version are you running? Do you see any errors in the web console? (https://developer.chrome.com/docs/devtools/console/)

**Comment by DavidIlie** [comment]
The latest version, and there are no errors in the console

**Comment by DavidIlie** [comment]
Nevermind, I had the wrong mattermost URL configured.
