### ISSUE TITLE
Only small icon is shown instead of picture itself

### ISSUE THREAD

**Issue by omginput** [mattermost/mattermost-plugin-memes#64]
![image](https://user-images.githubusercontent.com/8403565/199013148-f0749e3d-24cd-4098-b65e-884768f5a234.png)

Dunno why. In Windows Desktop App.

**Comment by hanzei** [comment]
Is there anything the client or server logs?

**Comment by omginput** [comment]
Mattermost runs on port 4443 not 443. May that be the issue? How can I tell it to use port 4443?

**Comment by hanzei** [comment]
What is the SiteURL that you configured in the system console?

**Comment by omginput** [comment]
I forgot the port there, that was it, thanks.
