### ISSUE TITLE
It seems all releases are for Windows only. Hence the .exe file in all releases.

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-memes#8]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/6324047/57257415-9e322f00-7059-11e9-9233-df80ffb03858.png">
distros

**Comment by hanzei** [comment]
The latest release on GitHub is build for darwin, linux and windows. Would you please try it out and see if it works.
![Screenshot from 2019-05-07 07-10-01](https://user-images.githubusercontent.com/16541325/57273218-3ac6f200-7097-11e9-808d-82d74fc1ebed.png)

**Comment by pnkz** [comment]
![image](https://user-images.githubusercontent.com/1215834/57697436-7fccc480-7653-11e9-94ec-afa6a5e59df4.png)

Same as before

**Comment by hanzei** [comment]
The executables just have the ending `.exe`. They are build for there respective os. E.g. the linux one is:

```
$ file plugin.exe 
plugin.exe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

**Comment by uhlhosting** [comment]
Confusing :)

**Comment by hanzei** [comment]
I know, but this is how it is. Open to a PR, if you want to fix this.
